import Head from 'next/head'
import Image from 'next/image'
import { FunctionComponent } from 'react'

const Home: FunctionComponent = () => {
  const handleClickControls = () => alert('Controls tapped')
  const handleClickMapView = () => alert('Map view tapped')
  const handleClickCarView = () => alert('Car view tapped')

  return (
    <div className="flex flex-col justify-between h-screen w-full p-12">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
      </Head>

      <main className='columns-2 h-full'>
        <div className="flex justify-center items-center bg-gray-900 rounded-lg h-full" onClick={handleClickCarView}>
          <h1 className="text-7xl">
            <a>Car view</a>
          </h1>
        </div>
        <div className="flex justify-center items-center bg-gray-600 rounded-lg h-full" onClick={handleClickMapView}>
          <h1 className="text-7xl">
            <a>Map view</a>
          </h1>
        </div>
      </main>
      <footer className='flex justify-between items-center  pb-10 pt-4 px-16 w-full bg-black rounded-lg' onClick={handleClickControls}>
        <span className='material-icons text-4xl'>drive_eta</span>
        <span className='material-icons text-4xl text-sky-400'>ac_unit</span>
        <span className='material-icons text-4xl text-red-700'>wb_sunny</span>
        <span className='material-icons text-4xl'>airline_seat_recline_normal</span>
        <p className='text-4xl' >20°</p>
        <span className='material-icons text-4xl'>mode_fan_off</span>
        <p className='text-4xl'>20°</p>
        <span className='material-icons text-4xl'>airline_seat_recline_normal</span>
        <span className='material-icons text-4xl'>music_note</span>
        <span className='material-icons text-4xl'>phone_iphone</span>
        <span className='material-icons text-4xl'>volume_up</span>
      </footer>
    </div>
  )
}

export default Home;
